apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv0
  labels:
    app: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: ~/GitCode/xtrabackup/mysql/0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
  labels:
    app: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: ~/GitCode/xtrabackup/mysql/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
  labels:
    app: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: ~/GitCode/xtrabackup/mysql/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cp